"""Implicit rules generated by the [global] settings.

Mirrors the manifest's generation logic so the TUI can show the user what
rules the global settings will actually produce, in the position where they
end up in the real (deployed) ruleset.

Effective chain order (verified against a real manifest run):
    top:    loopback   (-I inserts at the top of the chain)
            related and established
            icmp drop  (when icmp=false, before the section rules)
    middle: the section rules
    bottom: icmp allow (when icmp=true, after the section rules)
            log        (appended at the end of the chain)
            policy     (the chain default: the last action for unmatched
                        traffic)

Returned as (top_groups, bottom_groups); the caller places the section
rules in between.
"""

from __future__ import annotations

CHAINS = ("input", "output", "forward")


def _row(chain: str, action: str, comment: str) -> dict:
    return {
        "table": "filter", "chain": chain, "from": "any", "sport": "any",
        "to": "any", "proto": "any", "port": "any", "action": action,
        "target": "", "comment": comment,
    }


def implicit_rules(globals_: dict) -> tuple[list[tuple[str, list[dict]]],
                                           list[tuple[str, list[dict]]]]:
    """Return (top_groups, bottom_groups) for the global settings.

    Only groups that actually generate rules are included.
    """
    top: list[tuple[str, list[dict]]] = []
    bottom: list[tuple[str, list[dict]]] = []
    policy = globals_.get("policy", "accept")

    # loopback: the manifest emits '-I' which inserts at the TOP of the chain
    lo_rows = []
    for c in ("input", "output"):
        p = globals_.get(f"policy_{c}", policy)
        if p == "drop" and globals_.get("loopback") != "false":
            lo_rows.append(_row(c, "accept", "loopback"))
    if lo_rows:
        top.append(("global: loopback", lo_rows))

    # related and established
    if globals_.get("established") == "true":
        top.append(("global: related and established",
                    [_row(c, "accept", "established") for c in CHAINS]))

    # icmp: false -> drop before the section rules; true -> allow after them
    if globals_.get("icmp") == "false":
        top.append(("global: icmp", [_row("input", "drop", "icmp (blocked)")]))
    elif globals_.get("icmp") == "true":
        bottom.append(("global: icmp", [_row("input", "accept", "icmp")]))

    # log: appended at the end of each chain (catches unmatched traffic)
    log = globals_.get("log")
    if log:
        bottom.append(("global: log",
                       [_row(c, "log", f"log: {log}") for c in CHAINS]))

    # policy: the chain default - the last action for unmatched traffic
    p_rows = []
    for c in CHAINS:
        p = globals_.get(f"policy_{c}", policy)
        p_rows.append(_row(c, p.lower(), "policy"))
    bottom.append(("global: policy", p_rows))

    return top, bottom
